### ISSUE TITLE
error with multiple GPUs

### ISSUE THREAD

**Issue by LiewFeng** [yilundu/irem_code_release#2]
Thank you for your code! I can run it successfully with one GPU. But when I ran the code with multiple GPUs, I got the following error:

> Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/3dod2/Workspace/irem_code_release/train.py", line 690, in main_single
    sync_model(model)
  File "/3dod2/Workspace/irem_code_release/train.py", line 305, in sync_model
    for model in model:
TypeError: 'EBM' object is not iterable

Any suggestions? Thanks!

**Comment by yilundu** [comment]
Hi, 

I pushed an update -- does it work? I unfortunately have not tested the multigpu training code in a long time, so its a bit outdated

**Comment by LiewFeng** [comment]
It works now. Thanks for your quick reply!
